### ISSUE TITLE
Text enlargement suggestion

### ISSUE THREAD

**Issue by Marsoff9898** [SayakaIsBaka/sayaslicer#3]
Good morning.

Please enlarge the text of this program, especially when maximising the window.

Thanks.

**Comment by SayakaIsBaka** [comment]
I'll look into it, I don't know if it's easily feasible to do something dynamic (aka without restarting the program) but it should be relatively easy to make an option that applies on startup

**Comment by SayakaIsBaka** [comment]
Added in https://github.com/SayakaIsBaka/sayaslicer/commit/eff5e15bb52fec2291e17e86c3c4ffee455b50b5
